sudo: required
services:
  - docker

before_install: 
  - docker build -t binilbillu/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true binilbillu/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Docker-react-env"
  bucket_name: "elasticbeanstalk-us-east-1-749820668905"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: "$aws_access_key"
  secret_access_key: "$aws_secret_key"